name: .NET Core

on: [push]

jobs:
  BuildAndTestOnWindows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          3.1.x
          5.0.x
          6.0.100
          9.0.x
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test --configuration UnitTest -l "console;verbosity=detailed" --no-build -f net9.0

  TestOnLinux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          3.1.x
          5.0.x
          6.0.100
          9.0.x
    - name: Test
      run: dotnet test "tests/dotnetCampus.Configurations.Tests" --configuration Release -f net9.0

  TestOnMac:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          3.1.x
          5.0.x
          6.0.100
          9.0.x
    - name: Test
      run: dotnet test "tests/dotnetCampus.Configurations.Tests" --configuration Release -f net9.0